DROP DATABASE IF EXISTS stock_db;
DROP USER IF EXISTS `user`@`%`;
CREATE DATABASE IF NOT EXISTS stock_db;
CREATE USER IF NOT EXISTS `user`@`%` IDENTIFIED BY 'password';
GRANT ALL ON stock_db.* TO `user`@`%`;