DROP DATABASE IF EXISTS stockservice;
DROP USER IF EXISTS `stock_service`@`%`;
CREATE DATABASE IF NOT EXISTS stockservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `stock_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `stockservice`.* TO `stock_service`@`%`;
FLUSH PRIVILEGES;